Vagrant.configure("2") do |config|
	config.vm.box = "codetheorist/gitlab-ce"
        config.vm.define "gitlab" do |master|
	  master.vm.network "private_network", ip: "192.168.56.112"
	  master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	  master.vm.hostname = "gitlab"
	  master.vm.provider "virtualbox" do |vb|
		  vb.memory = "2048"
		  vb.cpus = "1"
		  vb.name = "gitlab"
	  end
      end
end
