Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine312"
	config.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: true
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	config.vm.hostname = "agloriosS"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.cpus = "1"
		vb.name = "aglorios"
	end
    config.vm.provision "shell", path: "./setup.sh"
end
